### PR TITLE
Configure build environment for Web-CAT.

### PR DESCRIPTION
**Pull request by mkhon**

### CODE REVIEW

**Comment by paulproteus** [comment]
Thanks! I'm testing this now in my own Vagrant to make sure the build environment it creates can do the build.

**Comment by paulproteus** [comment]
When I run this, I get:

```
BUILD FAILED
/vagrant/web-cat/Web-CAT/build.xml:287: /vagrant/web-cat/Web-CAT/${servlet.jar.dir} does not exist.

Total time: 13 minutes 5 seconds
```

seems like there is one small-ish problem left. Can you test it on a fresh virtual machine, and see if you get the same error?

For what it's worth, I made a few small changes. Here they are:

```
diff --git a/install.sh b/install.sh
index d08380b..bad2b2e 100755
--- a/install.sh
+++ b/install.sh
@@ -13,13 +13,13 @@ if [ ! -f /usr/bin/javac ] ; then
 fi

 # install WebObjects
-[ -f WOInstaller.jar ] || curl -# -O http://wocommunity.org/tools/WOInstaller.jar
+[ -f WOInstaller.jar ] || ( curl -# http://wocommunity.org/tools/WOInstaller.jar -o WOInstaller.jar.tmp && mv WOInstaller.jar.tmp WOInstaller.jar )
 wodir=/Library/WebObjects/Versions/WebObjects543
 sudo mkdir -p $wodir
-[ -d $wodir/Library/Frameworks/JavaXML.framework ] || sudo java -jar WOInstaller.jar 5.4.3 $wodir
+[ -d $wodir/Library/Frameworks/JavaXML.framework ] || ( sudo java -jar WOInstaller.jar 5.4.3 $wodir || (sudo rm -rf "$wodir" ; exit 1) )

 # install Wonder Frameworks
-[ -f Wonder-Frameworks.tar.gz ] || curl -# -O -L https://jenkins.wocommunity.org/job/Wonder/lastSuccessfulBuild/artifact/Root/Roots/Wonder-Frameworks.tar.gz
+[ -f Wonder-Frameworks.tar.gz ] || ( curl -# -L https://jenkins.wocommunity.org/job/Wonder/lastSuccessfulBuild/artifact/Root/Roots/Wonder-Frameworks.tar.gz -o Wonder-Frameworks.tar.gz.tmp && mv Wonder-Frameworks.tar.gz.tmp Wonder-Frameworks.tar.gz)
 sudo tar xfz Wonder-Frameworks.tar.gz -C $wodir/Library/Frameworks
```

But I don't think those have anything to do with it.

In fact, I have a request -- can you add a `.travis.yml` file, so we can verify that it builds by looking at the `travis-ci.org` log?

Thanks!

**Comment by mkhon** [comment]
servlet.jar.dir error is expected and it happens during javadoc generation

**Comment by mkhon** [comment]
So .war is built properly - javadoc is an issue that needs eventually be fixed but it is not critical for now

**Comment by paulproteus** [comment]
Oh, okay. Does it cause the script to `exit 1`? If so, can you fix things so it doesn't cause the script to exit with a failure status code?

Feel free to add a temporary hack like literally `mkdir ' /vagrant/web-cat/Web-CAT/${servlet.jar.dir}'`.

**Pull request merged**
